version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: tg-es
    environment:
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=changeme
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: tg-kib
    environment:
      ELASTICSEARCH_URL: http://tg-es:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - 5601:5601

# separate command
# run in the ES server for enrolling elastic agent server
#- sudo ./elastic-agent install     --fleet-server-es=http://localhost:9200   --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDI3NTc3NzcxNjk6RUc4Y1JwbGpRSjY0T3ZndEpkemcwQQ   --fleet-server-policy=499b5aa7-d214-5b5d-838b-3cd76469844e   --fleet-server-insecure-http
